create table team(
    team_id number generated by default on null as identity,
    name varchar2(200) not null,
    nationality varchar2(100),
    director varchar2(150),
    constraint team_pk primary key (team_id)
) tablespace data_cyclis;

create table cyclist(
    cyclist_id number generated by default on null as identity,
    full_name varchar2(200) not null,
    nationality varchar2(100),
    birthdate date,
    constraint cyclist_pk primary key (cyclist_id)
) tablespace data_cyclis;

create table membership(
    membership_id number generated by default on null as identity,
    cyclist_id number not null,
    team_id number not null,
    start_date date not null,
    end_date date,
    constraint membership_pk primary key (membership_id),
    constraint membership_fk_cyclist foreign key (cyclist_id) references cyclist(cyclist_id),
    constraint membership_fk_team foreign key (team_id) references team(team_id)
) tablespace data_cyclis;

create table race(
    race_id number generated by default on null as identity,
    name varchar2(200) not null,
    edition_year number(4) not null,
    num_stages number,
    total_km number(8,2),
    winner_id number,
    constraint race_pk primary key (race_id),
    constraint race_fk_winner foreign key (winner_id) references cyclist(cyclist_id)
) tablespace data_cyclis;

create table team_participation(
    participation_id number generated by default on null as identity,
    race_id number not null,
    team_id number not null,
    final_position number,
    constraint participation_pk primary key (participation_id),
    constraint participation_fk_race foreign key (race_id) references race(race_id),
    constraint participation_fk_team foreign key (team_id) references team(team_id),
    constraint uq_team_race unique (race_id, team_id)
) tablespace data_cyclis;

-- insertar equipos
insert into team (name, nationality, director) values ('Team Angeles','España','Juana Angeles');
insert into team (name, nationality, director) values ('Team Gonzales','Brasil','Antonio Gonzales');
insert into team (name, nationality, director) values ('Team Reategui','Colombia','Jose Reategui');
insert into team (name, nationality, director) values ('Team Seclen','Perú','Lucy Seclen');

-- insertar ciclistas
insert into cyclist (full_name, nationality, birthdate) values ('Juan Angeles','España',to_date('1996-11-01','yyyy-mm-dd'));
insert into cyclist (full_name, nationality, birthdate) values ('Zabdiel Angeles','España',to_date('1997-03-15','yyyy-mm-dd'));
insert into cyclist (full_name, nationality, birthdate) values ('Jesus Gonzales','Brasil',to_date('1991-02-10','yyyy-mm-dd'));
insert into cyclist (full_name, nationality, birthdate) values ('Pablo Reategui','Colombia',to_date('1995-05-05','yyyy-mm-dd'));
insert into cyclist (full_name, nationality, birthdate) values ('Marina Seclen','Perú',to_date('1994-05-16','yyyy-mm-dd'));

-- insertar contratos (membership)
insert into membership (cyclist_id, team_id, start_date, end_date)
  values ((select cyclist_id from cyclist where full_name='Juan Angeles'),
          (select team_id from team where name='Team Angeles'),
          to_date('2020-05-01','yyyy-mm-dd'),
          to_date('2025-12-31','yyyy-mm-dd'));

insert into membership (cyclist_id, team_id, start_date, end_date)
  values ((select cyclist_id from cyclist where full_name='Zabdiel Angeles'),
          (select team_id from team where name='Team Angeles'),
          to_date('2023-03-01','yyyy-mm-dd'),
          to_date('2025-12-31','yyyy-mm-dd'));

insert into membership (cyclist_id, team_id, start_date, end_date)
  values ((select cyclist_id from cyclist where full_name='Jesus Gonzales'),
          (select team_id from team where name='Team Gonzales'),
          to_date('2023-07-04','yyyy-mm-dd'),
          to_date('2025-12-31','yyyy-mm-dd'));

insert into membership (cyclist_id, team_id, start_date, end_date)
  values ((select cyclist_id from cyclist where full_name='Pablo Reategui'),
          (select team_id from team where name='Team Reategui'),
          to_date('2021-03-01','yyyy-mm-dd'),
          to_date('2025-12-31','yyyy-mm-dd'));
          
insert into membership (cyclist_id, team_id, start_date, end_date)
  values ((select cyclist_id from cyclist where full_name='Marina Seclen'),
          (select team_id from team where name='Team Seclen'),
          to_date('2022-01-01','yyyy-mm-dd'),
          to_date('2025-12-31','yyyy-mm-dd'));

-- insertar carrera
insert into race (name, edition_year, num_stages, total_km, winner_id)
  values ('Gran Premio Andino',2024,5,720.4,
          (select cyclist_id from cyclist where full_name='Juan Angeles'));

-- participación de equipos en la carrera
insert into team_participation (race_id, team_id, final_position)
  values ((select race_id from race where name='Gran Premio Andino' and edition_year=2024),
          (select team_id from team where name='Team Angeles'),
          1);

insert into team_participation (race_id, team_id, final_position)
  values ((select race_id from race where name='Gran Premio Andino' and edition_year=2024),
          (select team_id from team where name='Team Gonzales'),
          2);

insert into team_participation (race_id, team_id, final_position)
  values ((select race_id from race where name='Gran Premio Andino' and edition_year=2024),
          (select team_id from team where name='Team Reategui'),
          3);

insert into team_participation (race_id, team_id, final_position)
  values ((select race_id from race where name='Gran Premio Andino' and edition_year=2024),
          (select team_id from team where name='Team Seclen'),
          4);

commit;

-- 1) Equipos que no tienen ciclistas (sin contratos)
select t.name, t.director
from team t
left join membership m on t.team_id = m.team_id
where m.membership_id is null;

-- 2) Número de ciclistas por equipo (orden descendente)
select t.name as equipo, count(m.cyclist_id) as total_ciclistas
from team t
left join membership m on t.team_id = m.team_id
group by t.name
order by 2 desc, 1 asc;

-- 3) Ciclistas y su equipo actual (fecha de corte 2025-09-07)
select c.full_name, t.name as equipo, m.start_date, m.end_date
from cyclist c
join membership m on c.cyclist_id = m.cyclist_id
join team t on m.team_id = t.team_id
where date '2025-09-07' between m.start_date and nvl(m.end_date,date '2999-12-31');

-- 4) Clasificación final de la carrera "Gran Premio Andino" 2024
select tp.final_position, t.name as equipo, t.director
from team_participation tp
join team t on tp.team_id = t.team_id
join race r on tp.race_id = r.race_id
where r.name='Gran Premio Andino' and r.edition_year=2024
order by tp.final_position;

-- 5) Ganador de la carrera
select r.name, r.edition_year, c.full_name as ganador
from race r
join cyclist c on r.winner_id = c.cyclist_id
where r.name='Gran Premio Andino' and r.edition_year=2024;

SELECT COUNT(*) FROM cyclist;
